Added support for #EXT-X-SESSION-DATA tag in master playlist
yandex-pcode/hls.js pull request #1
Opened 2018-07-05 16:19 UTC by theifish

### This PR will add parsing for tag EXT-X-SESSION-DATA in master playlist.

### Why is this Pull Request needed?

There is extra tag in specification (https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-02#section-4.4.4.4) allows to deliver additional data to player. 
It would be usefull in several cases, for example, to mark some levels with special names on a backend side.

### Are there any points in the code the reviewer needs to double check?

No.

### Resolves issues:

-

### Checklist

- [x] changes have been done against master branch, and PR does not conflict
- [x] no commits have been done in dist folder (we will take care of updating it)
- [ ] new unit / functional tests have been added (whenever applicable)
- [x] API or design changes are documented in API.md

2018-07-05 19:00 UTC, mad-gooze requested changes
надо добавить тесты в https://github.com/yandex-pcode/hls.js/blob/master/tests/unit/loader/playlist-loader.js

2018-07-05 19:00 UTC, mad-gooze commented on src/loader/m3u8-parser.js
> +      level.sessionData = sessionData;
получается, одна и та же sessionData будет приклеиваться во все левелы?

2018-07-13 16:16 UTC, theifish commented on src/loader/m3u8-parser.js
> +      level.sessionData = sessionData;
Да, мне кажется так удобнее их вытаскивать и не надо потом дополнительно дестроить.

2018-07-14 12:39 UTC, mad-gooze approved these changes

2018-07-14 12:39 UTC, mad-gooze commented on tests/unit/loader/playlist-loader.js
> +  it('parses manifest with multiply EXT-X-SESSION-DATA', () => {
multiple

2018-07-14 12:41 UTC, mad-gooze commented on src/loader/m3u8-parser.js
> +      level.sessionData = sessionData;
мне кажется более логичным хранить ее в объекте hls, потому что sessionData не относится к конкретному левелу

впрочем, давайте посмотрим что мейнтейнеры hls.js скажут

2018-07-24 12:48 UTC, merged